-- 1) Average Cruise Rating by Cruise Line
SELECT 
    CRUISE_LINE.COMPANY_NAME, 
    ROUND(AVG(COMMUNITY_REVIEW.RATING), 2) AS AVERAGE_RATING
FROM CRUISE_LINE 
JOIN COMMUNITY_REVIEW ON  CRUISE_LINE.COMPANY_NAME = COMMUNITY_REVIEW.COMPANY_NAME
GROUP BY CRUISE_LINE.COMPANY_NAME
ORDER BY AVERAGE_RATING DESC;

-- 2) Price Per Day Ratio by Cruise Line
SELECT
   CRUISE_LINE.COMPANY_NAME,
   CRUISE_DEAL.DURATION,
   CRUISE_DEAL.PRICE,
   ROUND((CRUISE_DEAL.PRICE / CRUISE_DEAL.DURATION), 2) AS PRICE_PER_DAY
FROM CRUISE_LINE
JOIN CRUISE_DEAL
ON  CRUISE_LINE.COMPANY_NAME = CRUISE_DEAL.COMPANY_NAME
ORDER BY PRICE_PER_DAY DESC;

-- 3) Number of Posts Made by the User

SELECT
   USER_ACCOUNT.USERNAME,
   COUNT(DISCUSSES.FORUM_ID) AS POSTS_MADE
FROM USER_ACCOUNT
JOIN DISCUSSES ON USER_ACCOUNT.USER_ID = DISCUSSES.USER_ID
GROUP BY USER_ACCOUNT.USERNAME
ORDER BY POSTS_MADE DESC;



-- 4) Excursions Offered By Cruise Line

SELECT
  CRUISE_LINE.COMPANY_NAME,
  CRUISE_TRIP.ORIENTATION,
  CRUISE_TRIP_EXCURSIONS.EXCURSIONS
FROM CRUISE_LINE
JOIN CRUISE_TRIP ON CRUISE_LINE.COMPANY_NAME = CRUISE_TRIP.COMPANY_NAME
JOIN CRUISE_TRIP_EXCURSIONS ON CRUISE_TRIP.TRIP_ID = CRUISE_TRIP_EXCURSIONS.TRIP_ID;

-- 5) Average Cruise Price by Port Departure
SELECT 
    CRUISE_TRIP.DEPARTURE_PORT,
    ROUND(AVG(CRUISE_TRIP.PRICE), 2) AS AVG_PRICE
FROM CRUISE_TRIP
GROUP BY CRUISE_TRIP.DEPARTURE_PORT
ORDER BY AVG_PRICE DESC;

-- 6) Long-Term Trips 

SELECT
   TRIP_NAME,
   DURATION,
   PRICE
FROM CRUISE_TRIP
WHERE DURATION > 7
ORDER BY DURATION DESC;